### ISSUE TITLE
'secret' values not detected by JavaScript passwords check

### ISSUE THREAD

**Issue by JavaJimFl** [Skyscanner/sonar-secrets#2]
Would it be appropriate to add variations of 'secret' to the regex in the Passwords check?

`private static final Pattern PASSWORD_VARIABLES = Pattern.compile(".*(password|passwd|pwd|secret|scrt)$", Pattern.CASE_INSENSITIVE);`

I reviewed a script that had hard-coded API key and secret pairs, and while the Skyscanner plugin picked up the API key, it missed the hardcoded password/secret.

Thanks!

**Comment by adeptex** [comment]
Hi @JavaJimFl sorry for a veeeeery late reply on this. But better late than never!

What we have found is that including `secret` produces more false positives than useful findings. So excluding it from this list was intentional. 

If you'd like to include that term anyway, the easiest way would be adding it to the regex expression and recompiling the jars. If you have ideas on how to implement something configurable your PR is more than welcome :)

Closing this issue for now as I think this answers your question. Please feel free to reopen if needed!
